Optik Arayuz/Optik Arayuz UI/Models/Announcement.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Optik_Arayuz_UI.Models
{
    public class Announcement
    {
        [Key]
        public int AnnouncementId { get; set; }
        [Display(Name = "Duyuru Başlığı")]
        public string? AnnouncementName { get; set; }
        [Display(Name = "İçerik")]
        public string? AnnouncementContent { get; set; }
        [Display(Name = "Oluşturma Tarihi")]
        public string? AnnouncementDate { get; set; }
        [ForeignKey("User")]
        [Display(Name = "Oluşturan Kişi")]
        public string UserId { get; set; }
        public virtual User? User { get; set; }
    }
}

Optik Arayuz/Optik Arayuz UI/Areas/Admin/Controllers/AnnouncementsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Optik_Arayuz_UI.Data;
using Optik_Arayuz_UI.Models;

namespace Optik_Arayüz_UI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AnnouncementsController : Controller
    {
        private readonly OptikArayuzDbContext _context;
        private readonly UserManager<User> _userManager;
        public AnnouncementsController(OptikArayuzDbContext context,
            UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Admin/Announcements
        public async Task<IActionResult> Index()
        {
            var optikArayuzDbContext = _context.Announcements.Include(a => a.User);
            return View(await optikArayuzDbContext.ToListAsync());
        }

        // GET: Admin/Announcements/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Announcements == null)
            {
                return NotFound();
            }

            var announcement = await _context.Announcements
                .Include(a => a.User)
                .FirstOrDefaultAsync(m => m.AnnouncementId == id);
            if (announcement == null)
            {
                return NotFound();
            }

            return PartialView(announcement);
        }

        // GET: Admin/Announcements/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Announcements/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AnnouncementId,AnnouncementName,AnnouncementContent,AnnouncementDate,UserId")] Announcement announcement)
        {
            if (ModelState.IsValid)
            {
                announcement.UserId = _userManager.GetUserId(HttpContext.User);
                announcement.AnnouncementDate = DateTime.Now.ToString();
                _context.Add(announcement);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.User, "Id", "Id", announcement.UserId);
            return View(announcement);
        }

        // GET: Admin/Announcements/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Announcements == null)
            {
                return NotFound();
            }

            var announcement = await _context.Announcements.FindAsync(id);
            if (announcement == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.User, "Id", "Id", announcement.UserId);
            return PartialView(announcement);
        }

        // POST: Admin/Announcements/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AnnouncementId,AnnouncementName,AnnouncementContent,AnnouncementDate,UserId")] Announcement announcement)
        {
            if (id != announcement.AnnouncementId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(announcement);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AnnouncementExists(announcement.AnnouncementId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.User, "Id", "Id", announcement.UserId);
            return PartialView(announcement);
        }

        // GET: Admin/Announcements/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Announcements == null)
            {
                return NotFound();
            }

            var announcement = await _context.Announcements
                .Include(a => a.User)
                .FirstOrDefaultAsync(m => m.AnnouncementId == id);
            if (announcement == null)
            {
                return NotFound();
            }

            return PartialView(announcement);
        }

        // POST: Admin/Announcements/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Announcements == null)
            {
                return Problem("Entity set 'OptikArayuzDbContext.Announcements'  is null.");
            }
            var announcement = await _context.Announcements.FindAsync(id);
            if (announcement != null)
            {
                _context.Announcements.Remove(announcement);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AnnouncementExists(int id)
        {
          return (_context.Announcements?.Any(e => e.AnnouncementId == id)).GetValueOrDefault();
        }
    }
}

Optik Arayuz/Optik Arayuz UI/Areas/Admin/Views/Announcements/Create.cshtml
@model Optik_Arayuz_UI.Models.Announcement

@{
    ViewData["Title"] = "Create";
}

<head>

    <link rel="stylesheet" href="~/css/FormCard.css">
    <link rel="stylesheet" href="~/css/button.css">
</head>
<div class="Ccontainer">
    <div class="Card">
        <form asp-action="Create">
            <input asp-for="UserId" type="hidden" value="1" />
            <input asp-for="AnnouncementDate" type="hidden" value="1" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="Row">
                <label asp-for="AnnouncementName" class=""></label>
                <input asp-for="AnnouncementName" class="" />
                <span asp-validation-for="AnnouncementName" class="text-danger"></span>
            </div>
            <div class="Row">
                <label asp-for="AnnouncementContent" class=""></label>
                <input asp-for="AnnouncementContent" class="" />
                <span asp-validation-for="AnnouncementContent" class="text-danger"></span>
            </div>

            <div class="buton">
                <input type="submit" value="Oluştur" class="button" />
            </div>
        </form>
    </div>
    <div class="buton">
        <a class="button" asp-action="Index">Duyuru Listesine Dön</a>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Optik Arayuz/Optik Arayuz UI/Areas/Admin/Views/Announcements/Delete.cshtml
@model Optik_Arayuz_UI.Models.Announcement

@{
    ViewData["Title"] = "Delete";
}
<div class="Rcontainer">

<div>
        <h4>Duyuruyu Sil</h4>

        <p style="color:black">Silmek istediğinize emin misiniz?</p>
    <dl>
        <dt >
            @Html.DisplayNameFor(model => model.AnnouncementName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AnnouncementName)
        </dd>
        <dt >
            @Html.DisplayNameFor(model => model.AnnouncementContent)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AnnouncementContent)
        </dd>
        <dt >
            @Html.DisplayNameFor(model => model.AnnouncementDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AnnouncementDate)
        </dd>
        <dt >
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.User.FirstName)
        </dd>
    </dl>
    <form asp-action="Delete">
        <input type="hidden" asp-for="AnnouncementId" />
            <input type="submit" value="Sil" class="button" />
    </form>
</div>
</div>

Optik Arayuz/Optik Arayuz UI/Areas/Admin/Views/Announcements/Details.cshtml
@model Optik_Arayuz_UI.Models.Announcement

@{
    ViewData["Title"] = "Details";
}

<div class="Rcontainer">
    <h4>Duyuru</h4>
    <hr />
    <dl>
        <dt >
            @Html.DisplayNameFor(model => model.AnnouncementName)
        </dt>
        <dd >
            @Html.DisplayFor(model => model.AnnouncementName)
        </dd>
        <dt >
            @Html.DisplayNameFor(model => model.AnnouncementContent)
        </dt>
        <dd >
            @Html.DisplayFor(model => model.AnnouncementContent)
        </dd>
        <dt >
            @Html.DisplayNameFor(model => model.AnnouncementDate)
        </dt>
        <dd >
            @Html.DisplayFor(model => model.AnnouncementDate)
        </dd>
        <dt >
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd >
            @Html.DisplayFor(model => model.User.FirstName)
        </dd>
    </dl>
</div>

Optik Arayuz/Optik Arayuz UI/Areas/Admin/Views/Announcements/Edit.cshtml
@model Optik_Arayuz_UI.Models.Announcement

@{
    ViewData["Title"] = "Edit";
}
<head>
    <link rel="stylesheet" href="~/css/input.css" asp-append-version="true">

</head>
<div class="Rcontainer">

    <h4>Duyuruyu Düzenle&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</h4>
    <hr />
    <div class="">
        <div class="">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="AnnouncementId" />
                <input type="hidden" asp-for="UserId" />
                <input type="hidden" asp-for="AnnouncementDate" />
            <dl>
                <dt>
                        <label asp-for="AnnouncementName" ></label>

                </dt>
                <dd>
                        <input asp-for="AnnouncementName" class="input" />
                        <span asp-validation-for="AnnouncementName" class="text-danger"></span>
                </dd>
                    <dt>
                        <label asp-for="AnnouncementContent" ></label>

                    </dt>
                    <dd>
                        <input asp-for="AnnouncementContent" class="input" />
                        <span asp-validation-for="AnnouncementContent" class="text-danger"></span>
                    </dd>

            </dl>
            
                <input type="submit" value="Kaydet" class="button" />
        </form>
    </div>
</div>
</div>

Optik Arayuz/Optik Arayuz UI/Areas/Admin/Views/Announcements/Index.cshtml
@model IEnumerable<Optik_Arayuz_UI.Models.Announcement>

@{
    ViewData["Title"] = "Index";
}

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css">

    <!-- Style -->
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/button.css">

    <title>Duyurular</title>
</head>

<div class="content">

    <div class="container">
        <h2 class="mb-3" style="display:flex;justify-content:space-between;align-items:center;">Duyurular <a class='button blocked' asp-area="Admin" asp-controller="Announcements" asp-action="Create">Yeni Duyuru Oluştur</a></h2>

        <div class="table-responsive">

            <table class="table custom-table">
                <thead>
                    <tr>
                        <th scope="col">
                            @Html.DisplayNameFor(model => model.AnnouncementName)
                        </th>
                        <th scope="col">
                            @Html.DisplayNameFor(model => model.AnnouncementContent)
                        </th>
                        <th scope="col">
                            @Html.DisplayNameFor(model => model.AnnouncementDate)
                        </th>
                        <th scope="col">
                            @Html.DisplayNameFor(model => model.UserId)
                        </th>
                        <th scope="col"></th>
                    </tr>

                </thead>
                <tbody>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.AnnouncementName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.AnnouncementContent)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.AnnouncementDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.User.FirstName)
                            </td>
                            <td>
                                <a class='button Edit' id="@item.AnnouncementId">Düzenle</a> |
                                <a class='button Details' id="@item.AnnouncementId">Detaylar</a> |
                                <a class='button Delete' id="@item.AnnouncementId">Sil</a>
                            </td>
                        </tr>
                    }


                </tbody>
            </table>
        </div>

    </div>

</div>

<div class="content">
    <div id="rightContent">
        <div>
        </div>
    </div>
</div>

<script src="~/js/jquery-3.3.1.min.js"></script>
<script src="~/js/bootstrap.min.js"></script>
<script src="~/js/mainTable.js"></script>