Optik Arayuz/Optik Arayuz UI/Models/Faculty.cs
using System.ComponentModel.DataAnnotations;

namespace Optik_Arayuz_UI.Models
{
    public class Faculty
    {
        [Key]
        public int FacultyId { get; set; }
        [Display(Name = "Fakülte Adı")]
        public string? FacultyName { get; set; }
        [Display(Name = "Fakülte Adresi")]
        public string? FacultyAddress { get; set; }
        [Display(Name = "Fakülte Maili")]
        public string? FacultyMail { get; set; }
        [Display(Name = "Fakülte Numarası")]
        public string? FacultyPhoneNumber { get; set; }

    }
}

Optik Arayuz/Optik Arayuz UI/Areas/Admin/Controllers/FacultiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Optik_Arayuz_UI.Data;
using Optik_Arayuz_UI.Models;

namespace Optik_Arayüz_UI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]

    public class FacultiesController : Controller
    {
        private readonly OptikArayuzDbContext _context;

        public FacultiesController(OptikArayuzDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Faculties
        public async Task<IActionResult> Index()
        {
            return _context.Faculties != null ?
                        View(await _context.Faculties.ToListAsync()) :
                        Problem("Entity set 'OptikArayuzDbContext.Faculties'  is null.");
        }

        // GET: Admin/Faculties/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Faculties == null)
            {
                return NotFound();
            }

            var faculty = await _context.Faculties
                .FirstOrDefaultAsync(m => m.FacultyId == id);
            if (faculty == null)
            {
                return NotFound();
            }

            return PartialView(faculty);
        }

        // GET: Admin/Faculties/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Faculties/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FacultyId,FacultyName,FacultyAddress,FacultyMail,FacultyPhoneNumber")] Faculty faculty)
        {
            if (ModelState.IsValid)
            {
                _context.Add(faculty);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(faculty);
        }

        // GET: Admin/Faculties/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Faculties == null)
            {
                return NotFound();
            }

            var faculty = await _context.Faculties.FindAsync(id);
            if (faculty == null)
            {
                return NotFound();
            }
            return PartialView(faculty);
        }

        // POST: Admin/Faculties/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FacultyId,FacultyName,FacultyAddress,FacultyMail,FacultyPhoneNumber")] Faculty faculty)
        {
            if (id != faculty.FacultyId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(faculty);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FacultyExists(faculty.FacultyId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return PartialView(faculty);
        }

        // GET: Admin/Faculties/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Faculties == null)
            {
                return NotFound();
            }

            var faculty = await _context.Faculties
                .FirstOrDefaultAsync(m => m.FacultyId == id);
            if (faculty == null)
            {
                return NotFound();
            }

            return PartialView(faculty);
        }

        // POST: Admin/Faculties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Faculties == null)
            {
                return Problem("Entity set 'OptikArayuzDbContext.Faculties'  is null.");
            }
            var faculty = await _context.Faculties.FindAsync(id);
            if (faculty != null)
            {
                _context.Faculties.Remove(faculty);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FacultyExists(int id)
        {
            return (_context.Faculties?.Any(e => e.FacultyId == id)).GetValueOrDefault();
        }
    }
}

Optik Arayuz/Optik Arayuz UI/Areas/Admin/Views/Faculties/Create.cshtml
@model Optik_Arayuz_UI.Models.Faculty

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>

    <link rel="stylesheet" href="~/css/FormCard.css">
    <link rel="stylesheet" href="~/css/button.css">
</head>

<div class="Ccontainer">
    <div class="Card">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="Row">
                <label asp-for="FacultyName" class=""></label>
                <input asp-for="FacultyName" class="" />
                <span asp-validation-for="FacultyName" class="text-danger"></span>
            </div>
            <div class="Row">
                <label asp-for="FacultyAddress" class=""></label>
                <input asp-for="FacultyAddress" class="" />
                <span asp-validation-for="FacultyAddress" class="text-danger"></span>
            </div>
            <div class="Row">
                <label asp-for="FacultyMail" class=""></label>
                <input asp-for="FacultyMail" class="" />
                <span asp-validation-for="FacultyMail" class="text-danger"></span>
            </div>
            <div class="Row">
                <label asp-for="FacultyPhoneNumber" class=""></label>
                <input asp-for="FacultyPhoneNumber" class="" />
                <span asp-validation-for="FacultyPhoneNumber" class="text-danger"></span>
            </div>
            <div class="buton">
                <input type="submit" value="Oluştur" class="button" />
            </div>
        </form>
    </div>
    <div class="buton">
        <a class="button" asp-action="Index">Fakülte Listesine Dön</a>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Optik Arayuz/Optik Arayuz UI/Areas/Admin/Views/Faculties/Delete.cshtml
@model Optik_Arayuz_UI.Models.Faculty

@{
    ViewData["Title"] = "Delete";

}

<div class="Rcontainer">
    <h4>Fakülteyi Sil</h4>

    <p style="color:black">Silmek istediğinize emin misiniz?</p>
    <div>
        <hr />
        <dl>
        <dt >
            @Html.DisplayNameFor(model => model.FacultyName)
        </dt>
        <dd >
            @Html.DisplayFor(model => model.FacultyName)
        </dd>
        <dt >
            @Html.DisplayNameFor(model => model.FacultyAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FacultyAddress)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FacultyMail)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FacultyMail)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FacultyPhoneNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FacultyPhoneNumber)
        </dd>
    </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="FacultyId" />
            <input type="submit" value="Sil" class="button" />
        </form>
    </div>
</div>

Optik Arayuz/Optik Arayuz UI/Areas/Admin/Views/Faculties/Details.cshtml
@model Optik_Arayuz_UI.Models.Faculty

@{
    ViewData["Title"] = "Details";

}
<div class="Rcontainer">
    <div>
        <h4>Fakülte</h4>
        <hr />
        <dl class="">
            <dt class="">
                Fakülte Adı
            </dt>
            <dd class="">
                @Html.DisplayFor(model => model.FacultyName)
            </dd>
            <dt class="">
                Fakülte Adresi
            </dt>
            <dd class="">
                @Html.DisplayFor(model => model.FacultyAddress)
            </dd>
            <dt class="">
                Fakülte Mail
            </dt>
            <dd class="">
                @Html.DisplayFor(model => model.FacultyMail)
            </dd>
            <dt class="">
                Fakülte Numarası
            </dt>
            <dd class="">
                @Html.DisplayFor(model => model.FacultyPhoneNumber)
            </dd>
        </dl>
    </div>

</div>

Optik Arayuz/Optik Arayuz UI/Areas/Admin/Views/Faculties/Edit.cshtml
@model Optik_Arayuz_UI.Models.Faculty

@{
    ViewData["Title"] = "Edit";

}

<link rel="stylesheet" href="~/css/input.css" asp-append-version="true">

<div class="Rcontainer">

    <h4>Fakülteyi Düzenle&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</h4>
    <hr />
    <div class="">
        <div class="">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="FacultyId" />
                <dl>
                    <dt>
                        <label asp-for="FacultyName"></label>
                    </dt>
                    <dd>
                        <input asp-for="FacultyName" class="input" />
                        <span asp-validation-for="FacultyName" class="text-danger"></span>
                    </dd>
                    <dt>
                        <label asp-for="FacultyAddress" ></label>

                    </dt>
                    <dd>
                        <input asp-for="FacultyAddress" class="input" />
                        <span asp-validation-for="FacultyAddress" class="text-danger"></span>
                    </dd>
                    <dt>
                        <label asp-for="FacultyMail" ></label>

                    </dt>
                    <dd>
                        <input asp-for="FacultyMail" class="input" />
                        <span asp-validation-for="FacultyMail" class="text-danger"></span>
                    </dd>
                    <dt>
                        <label asp-for="FacultyPhoneNumber" ></label>

                    </dt>
                    <dd>
                        <input asp-for="FacultyPhoneNumber" class="input" />
                        <span asp-validation-for="FacultyPhoneNumber" class="text-danger"></span>
                    </dd>
                    
                    
                </dl>

                <input type="submit" value="Kaydet" class="button" />

            </form>
        </div>
    </div>


</div>

Optik Arayuz/Optik Arayuz UI/Areas/Admin/Views/Faculties/Index.cshtml
@model IEnumerable<Optik_Arayuz_UI.Models.Faculty>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css">

    <!-- Style -->
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true">
    <link rel="stylesheet" href="~/css/button.css" asp-append-version="true">

    <title>Fakülteler</title>
</head>

<div class="content">

    <div class="container">
        <h2 class="mb-3" style="display:flex;justify-content:space-between;align-items:center;">Fakülteler <a class="button blocked" asp-area="Admin" asp-controller="Faculties" asp-action="Create">Yeni Fakülte Oluştur</a></h2>

        <div class="table-responsive">

            <table class="table custom-table">
                <thead>
                    <tr>
                        <th scope="col">Fakülte Adı</th>
                        <th scope="col">Fakülte Adresi</th>
                        <th scope="col">Fakülte Mail</th>
                        <th scope="col">Fakülte İletişim</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.FacultyName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FacultyAddress)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FacultyMail)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FacultyPhoneNumber)
                            </td>
                            <td>
                                <a class='button Edit' id="@item.FacultyId">Düzenle</a>
                                <a class='button Details' id="@item.FacultyId">Detaylar</a>
                                <a class='button Delete' id="@item.FacultyId">Sil </a>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>


    </div>

</div>
<div class="content">
    <div id="rightContent">
        <div>
        </div>
    </div>
</div>
<script src="~/js/jquery-3.3.1.min.js"></script>
<script src="~/js/popper.min.js"></script>
<script src="~/js/bootstrap.min.js"></script>
<script src="~/js/mainTable.js" asp-append-version="true"></script>