Optik Arayuz/Optik Arayuz UI/Models/Department.cs
using Optik_Arayuz_UI.Models;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Optik_Arayuz_UI.Models
{
    public class Department
    {
        [Key]
        public int DepartmentId { get; set; }
        [Display(Name = "Departman Adı")]
        public string? DepartmentName { get; set; }
        [Display(Name = "Departman Adresi")]
        public string? DepartmentAddress { get; set; }
        [Display(Name = "Departman Maili")]
        public string? DepartmentMail { get; set; }
        [Display(Name = "Departman Numarası")]
        public string? DepartmentPhoneNumber { get; set; }

        [ForeignKey("Faculty")]
        [Display(Name = "Fakülte Adı")]

        public int? FacultyId { get; set; }
        public virtual Faculty? Faculty { get; set; }
    }
}

Optik Arayuz/Optik Arayuz UI/Areas/Admin/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Optik_Arayuz_UI.Data;
using Optik_Arayuz_UI.Models;

namespace Optik_Arayuz_UI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]

    public class DepartmentsController : Controller
    {
        private readonly OptikArayuzDbContext _context;

        public DepartmentsController(OptikArayuzDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Departments
        public async Task<IActionResult> Index()
        {
            var optikArayuzDbContext = _context.Departments.Include(d => d.Faculty);
            return View(await optikArayuzDbContext.ToListAsync());
        }

        // GET: Admin/Departments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Departments == null)
            {
                return NotFound();
            }

            var department = await _context.Departments
                .Include(d => d.Faculty)
                .FirstOrDefaultAsync(m => m.DepartmentId == id);
            if (department == null)
            {
                return NotFound();
            }

            return PartialView(department);
        }

        // GET: Admin/Departments/Create
        public IActionResult Create()
        {
            ViewData["FacultyId"] = new SelectList(_context.Faculties, "FacultyId", "FacultyName");
            return View();
        }

        // POST: Admin/Departments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DepartmentId,DepartmentName,DepartmentAddress,DepartmentMail,DepartmentPhoneNumber,FacultyId")] Department department)
        {
            if (ModelState.IsValid)
            {
                _context.Add(department);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FacultyId"] = new SelectList(_context.Faculties, "FacultyId", "FacultyName", department.FacultyId);
            return View(department);
        }

        // GET: Admin/Departments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Departments == null)
            {
                return NotFound();
            }

            var department = await _context.Departments.FindAsync(id);
            if (department == null)
            {
                return NotFound();
            }
            ViewData["FacultyId"] = new SelectList(_context.Faculties, "FacultyId", "FacultyName", department.FacultyId);
            return PartialView(department);
        }

        // POST: Admin/Departments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DepartmentId,DepartmentName,DepartmentAddress,DepartmentMail,DepartmentPhoneNumber,FacultyId")] Department department)
        {
            if (id != department.DepartmentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(department);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DepartmentExists(department.DepartmentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FacultyId"] = new SelectList(_context.Faculties, "FacultyId", "FacultyName", department.FacultyId);
            return PartialView(department);
        }

        // GET: Admin/Departments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Departments == null)
            {
                return NotFound();
            }

            var department = await _context.Departments
                .Include(d => d.Faculty)
                .FirstOrDefaultAsync(m => m.DepartmentId == id);
            if (department == null)
            {
                return NotFound();
            }

            return PartialView(department);
        }

        // POST: Admin/Departments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Departments == null)
            {
                return Problem("Entity set 'OptikArayuzDbContext.Departments'  is null.");
            }
            var department = await _context.Departments.FindAsync(id);
            if (department != null)
            {
                _context.Departments.Remove(department);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DepartmentExists(int id)
        {
          return (_context.Departments?.Any(e => e.DepartmentId == id)).GetValueOrDefault();
        }
    }
}

Optik Arayuz/Optik Arayuz UI/Areas/Admin/Views/Departments/Create.cshtml
@model Optik_Arayuz_UI.Models.Department

@{
    ViewData["Title"] = "Create";
}

<head>

    <link rel="stylesheet" href="~/css/FormCard.css">
    <link rel="stylesheet" href="~/css/button.css">
</head>

<div class="Ccontainer">
    <div class="Card">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="Row">
                <label asp-for="DepartmentName" class=""></label>
                <input asp-for="DepartmentName" class="" />
                <span asp-validation-for="DepartmentName" class="text-danger"></span>
            </div>
            <div class="Row">
                <label asp-for="DepartmentAddress" class=""></label>
                <input asp-for="DepartmentAddress" class="" />
                <span asp-validation-for="DepartmentAddress" class="text-danger"></span>
            </div>
            <div class="Row">
                <label asp-for="DepartmentMail" class=""></label>
                <input asp-for="DepartmentMail" class="" />
                <span asp-validation-for="DepartmentMail" class="text-danger"></span>
            </div>
            <div class="Row">
                <label asp-for="DepartmentPhoneNumber" class=""></label>
                <input asp-for="DepartmentPhoneNumber" class="" />
                <span asp-validation-for="DepartmentPhoneNumber" class="text-danger"></span>
            </div>
            <div class="Row">
                <label asp-for="FacultyId" class=""></label>
                <select asp-for="FacultyId" class ="" asp-items="ViewBag.FacultyId"></select>
            </div>
            <div class="buton">
                <input type="submit" value="Oluştur" class="button" />
            </div>
        </form>
    </div>
    <div class="buton">
        <a class="button" asp-action="Index">Listeye Dön</a>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Optik Arayuz/Optik Arayuz UI/Areas/Admin/Views/Departments/Delete.cshtml
@model Optik_Arayuz_UI.Models.Department

@{
    ViewData["Title"] = "Delete";
}
<div class="Rcontainer">
    <h4>Departmanı Sil</h4>

    <p style="color:black">Silmek istediğinize emin misiniz?</p>
    <div>
        <hr />
        <dl>
            <dt >
                @Html.DisplayNameFor(model => model.DepartmentName)
            </dt>
            <dd >
                @Html.DisplayFor(model => model.DepartmentName)
            </dd>
            <dt >
                @Html.DisplayNameFor(model => model.DepartmentAddress)
            </dt>
            <dd >
                @Html.DisplayFor(model => model.DepartmentAddress)
            </dd>
            <dt >
                @Html.DisplayNameFor(model => model.DepartmentMail)
            </dt>
            <dd >
                @Html.DisplayFor(model => model.DepartmentMail)
            </dd>
            <dt >
                @Html.DisplayNameFor(model => model.DepartmentPhoneNumber)
            </dt>
            <dd >
                @Html.DisplayFor(model => model.DepartmentPhoneNumber)
            </dd>
            <dt >
                @Html.DisplayNameFor(model => model.Faculty)
            </dt>
            <dd >
                @Html.DisplayFor(model => model.Faculty.FacultyName)
            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="DepartmentId" />
            <input type="submit" value="Sil" class="button" />
        </form>

    </div>
</div>

Optik Arayuz/Optik Arayuz UI/Areas/Admin/Views/Departments/Details.cshtml
@model Optik_Arayuz_UI.Models.Department

@{
    ViewData["Title"] = "Details";
}

<div class="Rcontainer">
    <div>
        <h4>Departman</h4>
        <hr />
    <dl>
        <dt >
            @Html.DisplayNameFor(model => model.DepartmentName)
        </dt>
        <dd >
            @Html.DisplayFor(model => model.DepartmentName)
        </dd>
        <dt >
            @Html.DisplayNameFor(model => model.DepartmentAddress)
        </dt>
        <dd >
            @Html.DisplayFor(model => model.DepartmentAddress)
        </dd>
        <dt >
            @Html.DisplayNameFor(model => model.DepartmentMail)
        </dt>
        <dd >
            @Html.DisplayFor(model => model.DepartmentMail)
        </dd>
        <dt >
            @Html.DisplayNameFor(model => model.DepartmentPhoneNumber)
        </dt>
        <dd >
            @Html.DisplayFor(model => model.DepartmentPhoneNumber)
        </dd>
        <dt >
            @Html.DisplayNameFor(model => model.FacultyId)
        </dt>
        <dd >
            @Html.DisplayFor(model => model.Faculty.FacultyId)
        </dd>
    </dl>
    </div>

</div>

Optik Arayuz/Optik Arayuz UI/Areas/Admin/Views/Departments/Edit.cshtml
@model Optik_Arayuz_UI.Models.Department

@{
    ViewData["Title"] = "Edit";
}
<link rel="stylesheet" href="~/css/input.css" asp-append-version="true">

<div class="Rcontainer">

    <h4>Departmanı Düzenle &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</h4>
    <hr />
    <div class="">
        <div class="">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="DepartmentId" />
                <dl>
                    <dt>
                        <label asp-for="DepartmentName" ></label>
                    </dt>
                    <dd>
                        <input asp-for="DepartmentName" class="input" />
                        <span asp-validation-for="DepartmentName" class="text-danger"></span>
                    </dd>
                    <dt>
                        <label asp-for="DepartmentAddress" ></label>
                    </dt>
                    <dd>
                        <input asp-for="DepartmentAddress" class="input" />
                        <span asp-validation-for="DepartmentAddress" class="text-danger"></span>
                    </dd>
                    <dt>
                        <label asp-for="DepartmentMail" ></label>

                    </dt>
                    <dd>
                        <input asp-for="DepartmentMail" class="input" />
                        <span asp-validation-for="DepartmentMail" class="text-danger"></span>
                    </dd>
                    <dt>
                        <label asp-for="DepartmentPhoneNumber" ></label>
                    </dt>
                    <dd>
                        <input asp-for="DepartmentPhoneNumber" class="input" />
                        <span asp-validation-for="DepartmentPhoneNumber" class="text-danger"></span>
                    </dd>
                    <dt>
                        <label asp-for="FacultyId" ></label>
                    </dt>
                    <dd>
                        <select asp-for="FacultyId" class="input" asp-items="ViewBag.FacultyId"></select>
                        <span asp-validation-for="FacultyId" class="text-danger"></span>
                    </dd>

                </dl>

                <input type="submit" value="Kaydet" class="button" />

            </form>
        </div>
    </div>

</div>

Optik Arayuz/Optik Arayuz UI/Areas/Admin/Views/Departments/Index.cshtml
@model IEnumerable<Optik_Arayuz_UI.Models.Department>

@{
    ViewData["Title"] = "Index";
}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css">

    <!-- Style -->
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true">
    <link rel="stylesheet" href="~/css/button.css" asp-append-version="true">

    <title>Bölümler</title>
</head>

<div class="content">

    <div class="container">
        <h2 class="mb-3" style="display:flex;justify-content:space-between;align-items:center;">Bölümler <a class="button blocked" asp-area="Admin" asp-controller="Departments" asp-action="Create">Departman Oluştur</a></h2>

        <div class="table-responsive">

            <table class="table custom-table">
                <thead>
                    <tr>
                        <th scope="col">
                            @Html.DisplayNameFor(model => model.DepartmentName)
                        </th>
                        <th scope="col">
                            @Html.DisplayNameFor(model => model.DepartmentAddress)
                        </th>
                        <th scope="col">
                            @Html.DisplayNameFor(model => model.DepartmentMail)
                        </th>
                        <th scope="col">
                            @Html.DisplayNameFor(model => model.DepartmentPhoneNumber)
                        </th>
                        <th scope="col">
                            @Html.DisplayNameFor(model => model.FacultyId)
                        </th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.DepartmentName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DepartmentAddress)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DepartmentMail)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DepartmentPhoneNumber)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Faculty.FacultyName)
                            </td>
                            <td>
                                <a class='button Edit' id="@item.DepartmentId">Düzenle</a>
                                <a class='button Details' id="@item.DepartmentId">Detaylar</a>
                                <a class='button Delete' id="@item.DepartmentId">Sil</a>
                            </td>
                        </tr>
                    }


                </tbody>
            </table>
        </div>


    </div>

</div>
<div class="content">
    <div id="rightContent">
        <div>
        </div>
    </div>
</div>
<script src="~/js/jquery-3.3.1.min.js"></script>
<script src="~/js/popper.min.js"></script>
<script src="~/js/bootstrap.min.js"></script>
<script src="~/js/mainTable.js" asp-append-version="true"></script>