Optik Arayuz/Optik Arayuz UI/Controllers/ExamPapersController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.V4.Pages.Account.Internal;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.Operations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Newtonsoft.Json.Linq;
using Optik_Arayuz_UI.Data;
using Optik_Arayuz_UI.Models;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Optik_Arayüz_UI.Controllers
{
    public class ExamPapersController : Controller
    {
        private readonly OptikArayuzDbContext _context;

        public ExamPapersController(OptikArayuzDbContext context)
        {
            ComponentsPartial componentsPartial = new ComponentsPartial(context);
            _context = context;
        }
        [Authorize]

        public IActionResult ExamPaperCreate(int? id)
        {
            clear();
            if (id != null)
            {
                ViewBag.Id = id;
            }
            return View();

        }

        [HttpPost]
        public IActionResult ExamPaperCreate(ExamPaper examPaper)
        {
            if (ModelState.IsValid) {
                _context.ExamPapers.Add(examPaper);

                _context.SaveChanges();
            }
           
            return View();

        }
        public bool ExamPaperCopy(int? id)
        {
            //Sınav Kağıdını Kopyalama işlemini gerçekleştiren fonksiyon.

            //Öncelikle kopyalanan kağıdın nameine Kopya ibaresi eklenerek yeniden ekleniyor ve Idsi alınıyor.
            var exampaper = _context.ExamPapers.First(m => m.ExamPaperId == id);
            exampaper.ExamPaperId = 0;
            exampaper.ExamPaperName = exampaper.ExamPaperName + " Kopya";

            _context.ExamPapers.Add(exampaper);
            _context.SaveChanges();
            var paperId = _context.ExamPapers.OrderBy(m => m.ExamPaperId).Last().ExamPaperId;
            //Kopyalanacak kağıdın bütün elementleri getiriliyor.
            var elements = _context.ExamPaperElements.Where(m => m.ExamPaperId == id).ToList();
            //Her elementin sınav kağıdı Idsi yeni ıd ile güncellenerek tekrardan ekleniyor.
            foreach (var element in elements) { 
                element.ExamPaperElementId = 0;
                element.ExamPaperId = paperId;
                _context.ExamPaperElements.Add(element);
            }
            _context.SaveChanges();
            //Her Elementin belirttiği componentler getirtilip onlarda kopyalanıyor. Yeni ıdleri examPapersElements kayıtınında yerini alıyor.
            var components = _context.ExamPaperElements.Where(m => m.ExamPaperId == paperId).ToList();
            foreach (var component in components) {
                switch (component.Type)
                {
                    case "Choice":
                        var a = _context.Choices.First(m => m.ChoiceId == component.ComponentId);
                        a.ChoiceId = 0;
                        _context.Choices.Add(a);
                        _context.SaveChanges();
                        var componentId = _context.Choices.OrderBy(m => m.ChoiceId).Last().ChoiceId;
                        component.ComponentId = componentId;
                        break;

                    case "Logo":
                        var b = _context.Logos.First(m => m.LogoId == component.ComponentId);
                        b.LogoId = 0;
                        _context.Logos.Add(b);
                        _context.SaveChanges();
                        var logoId = _context.Logos.OrderBy(m => m.LogoId).Last().LogoId;
                        component.ComponentId = logoId;
                        break;
                    case "Number":
                        var c = _context.Numbers.First(m => m.NumberId == component.ComponentId);
                        c.NumberId = 0;
                        _context.Numbers.Add(c);
                        _context.SaveChanges();
                        var numberId = _context.Numbers.OrderBy(m => m.NumberId).Last().NumberId;
                        component.ComponentId = numberId;
                        break;

                    case "Student":
                        var d = _context.Students.First(m => m.StudentId == component.ComponentId);
                        d.StudentId = 0;
                        _context.Students.Add(d);
                        _context.SaveChanges();
                        var studentId = _context.Students.OrderBy(m => m.StudentId).Last().StudentId;
                        component.ComponentId = studentId;
                        break;

                    case "Grade":
                        var e = _context.Grades.First(m => m.GradeId == component.ComponentId);
                        e.GradeId = 0;
                        _context.Grades.Add(e);
                        _context.SaveChanges();
                        var gradeId = _context.Grades.OrderBy(m => m.GradeId).Last().GradeId;
                        component.ComponentId = gradeId;
                        break;

                    case "Text":
                        var f = _context.Texts.First(m => m.TextId == component.ComponentId);
                        f.TextId = 0;
                        _context.Texts.Add(f);
                        _context.SaveChanges();
                        var textId = _context.Texts.OrderBy(m => m.TextId).Last().TextId;
                        component.ComponentId = textId;
                        break;

                    case "Test":
                        var g = _context.Tests.First(m => m.TestId == component.ComponentId);
                        g.TestId = 0;
                        _context.Tests.Add(g);
                        _context.SaveChanges();
                        var testId = _context.Tests.OrderBy(m => m.TestId).Last().TestId;
                        component.ComponentId = testId;
                        break;

                    default:
                        break;
                }
                _context.ExamPaperElements.Update(component);
                _context.SaveChanges();

            }
            return true;

        }
        public int CreateNewComponent(string type, int index)
        {
            //Elementin  kendi tablosunda yeni kayıt oluşturma fonksiyonu. Oluşturduktan sonra İd bilgisi geri döndürülür.
            switch (type)
            {
                case "Choice":
                    _context.Choices.Add(ComponentsPartial._choices[index]);
                    _context.SaveChanges();

                    return _context.Choices.OrderBy(m => m.ChoiceId).Last().ChoiceId;
                case "Logo":
                    _context.Logos.Add(ComponentsPartial._logos[index]);
                    _context.SaveChanges();

                    return _context.Logos.OrderBy(m => m.LogoId).Last().LogoId;
                case "Number":
                    _context.Numbers.Add(ComponentsPartial._numbers[index]);
                    _context.SaveChanges();

                    return _context.Numbers.OrderBy(m => m.NumberId).Last().NumberId;
                case "Student":
                    _context.Students.Add(ComponentsPartial._students[index]);
                    _context.SaveChanges();

                    return _context.Students.OrderBy(m => m.StudentId).Last().StudentId;

                case "Grade":
                    _context.Grades.Add(ComponentsPartial._grades[index]);
                    _context.SaveChanges();

                    return _context.Grades.OrderBy(m => m.GradeId).Last().GradeId;
                case "Text":
                    _context.Texts.Add(ComponentsPartial._texts[index]);
                    _context.SaveChanges();

                    return _context.Texts.OrderBy(m => m.TextId).Last().TextId;
                case "Test":
                    _context.Tests.Add(ComponentsPartial._tests[index]);
                    _context.SaveChanges();

                    return _context.Tests.OrderBy(m => m.TestId).Last().TestId;
                default:
                    return 0;


            }
        }
        public bool CreateNewExamPaper(string[] components)
        {
            var paperId = _context.ExamPapers.OrderBy(m => m.ExamPaperId).Last().ExamPaperId;
            int id = 0;
            //Her elementin öncelikle kendi tablosunda yeni kaydı oluşturulur. Daha sonra ExamPaperElements tablosunda yeni kayıt oluşturularak konum ve tür bilgileri kaydedilir.
            //Yeni kayıta sınavKağıdı id bilgisi verilerek kağıtların elementleri oluşturulur.
            for (int i = 0; i < components.Length; i++)
            {
                var attr = components[i].Split("_");
                int index = Convert.ToInt32(attr[0].Substring(attr[0].Length - 1));
                var type = attr[0][..^1];
                //Elementin  kendi tablosunda yeni kayıt oluşturma fonksiyonu. Oluşturduktan sonra İd bilgisi geri döndürülür.
                id = CreateNewComponent(type, index);

                ExamPaperElement examPaperElement = new ExamPaperElement()
                {
                    Type = type,
                    X = Convert.ToDouble(attr[1]),
                    Y = Convert.ToDouble(attr[2]),
                    ExamPaperId = paperId,
                    ComponentId = id,
                };
                _context.ExamPaperElements.Add(examPaperElement);
                _context.SaveChanges();

            }
            return true;
        }
        public string SendDatabase(string value)
        {
            //Elementleri Veritabanına gönderen fonksiyon. Eğer başında id var ise edit sayfasıdır. Yok ise yeni oluşturulmuştur. Farklı işlemler yapılacaktır.
            string[] components = value.Split("/");

Optik Arayuz/Optik Arayuz UI/Controllers/ExamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Optik_Arayuz_UI.Data;
using Optik_Arayuz_UI.Models;

namespace Optik_Arayüz_UI.Controllers
{
    public class ExamsController : Controller
    {
        private readonly OptikArayuzDbContext _context;
        private readonly UserManager<User> _userManager;

        public ExamsController(OptikArayuzDbContext context,
            UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;

        }
        // GET: Exams
        public async Task<IActionResult> Index()
        {
            var optikArayuzDbContext = _context.Exams.Include(e => e.ExamPaper).Include(e => e.User);
            return View(await optikArayuzDbContext.ToListAsync());
        }

        // GET: Exams/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Exams == null)
            {
                return NotFound();
            }

            var exam = await _context.Exams
                .Include(e => e.ExamPaper)
                .Include(e => e.User)
                .FirstOrDefaultAsync(m => m.ExamId == id);
            if (exam == null)
            {
                return NotFound();
            }

            return PartialView(exam);
        }

        // GET: Exams/Create
        public IActionResult Create()
        {
            ViewData["ExamPaperId"] = new SelectList(_context.ExamPapers, "ExamPaperId", "ExamPaperName");
            ViewData["UserId"] = "1";

            return View();
        }

        // POST: Exams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ExamId,ExamName,TestCount,ClassicCount,ExamPaperId,UserId")] Exam exam)
        {
            if (ModelState.IsValid)
            {
                exam.UserId = _userManager.GetUserId(HttpContext.User);
                _context.Add(exam);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ExamPaperId"] = new SelectList(_context.ExamPapers, "ExamPaperId", "ExamPaperId", exam.ExamPaperId);
            ViewData["UserId"] = new SelectList(_context.User, "Id", "Id", exam.UserId);
            return View(exam);
        }

        // GET: Exams/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Exams == null)
            {
                return NotFound();
            }

            var exam = await _context.Exams.FindAsync(id);
            if (exam == null)
            {
                return NotFound();
            }
            ViewData["ExamPaperId"] = new SelectList(_context.ExamPapers, "ExamPaperId", "ExamPaperName", exam.ExamPaperId);
            return PartialView(exam);
        }

        // POST: Exams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ExamId,ExamName,TestCount,ClassicCount,ExamPaperId,UserId")] Exam exam)
        {
            if (id != exam.ExamId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                exam.UserId = _userManager.GetUserId(HttpContext.User);
                try
                {
                    _context.Update(exam);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ExamExists(exam.ExamId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ExamPaperId"] = new SelectList(_context.ExamPapers, "ExamPaperId", "ExamPaperName", exam.ExamPaperId);
            return PartialView(exam);
        }

        // GET: Exams/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Exams == null)
            {
                return NotFound();
            }

            var exam = await _context.Exams
                .Include(e => e.ExamPaper)
                .Include(e => e.User)
                .FirstOrDefaultAsync(m => m.ExamId == id);
            if (exam == null)
            {
                return NotFound();
            }

            return PartialView(exam);
        }

        // POST: Exams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Exams == null)
            {
                return Problem("Entity set 'OptikArayuzDbContext.Exams'  is null.");
            }
            var exam = await _context.Exams.FindAsync(id);
            if (exam != null)
            {
                _context.Exams.Remove(exam);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ExamExists(int id)
        {
          return (_context.Exams?.Any(e => e.ExamId == id)).GetValueOrDefault();
        }
    }
}

Optik Arayuz/Optik Arayuz UI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.Extensions.Localization
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Optik Arayüz</title>

    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />


</head>
<body>
    @if (SignInManager.IsSignedIn(User))
    {
    <header>
            <nav class="Nav">
            <div class="NavLeft">
                <div class="NavLeftItem">
                        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img style="width:30px; height:30px;" src=@Url.Content("~/SauLogo.png") /></a>
                </div>

                <div class="NavLeftItem">
                    <a class="" asp-area="" asp-controller="Home" asp-action="Index">Ana Sayfa</a>
                </div>
                <div class="NavLeftItem">
                    <div class="myDropdown">
                            <a class="link" asp-area="" asp-controller="Exams" asp-action="Index">Sınavlar <span class="ArrowRight">></span> <span class="ArrowDown">v</span></a>
                            <div class="myContent">
                                <a class="" asp-area="" asp-controller="Exams" asp-action="Index">Listele</a>
                                <a class="" asp-area="" asp-controller="Exams" asp-action="Create">Yeni Oluştur</a>
                            </div>
                    </div>
                </div>
                <div class="NavLeftItem">
                        <div class="myDropdown">
                            <a class="link" asp-area="" asp-controller="ExamPapers" asp-action="Index">Sınav Kağıtları <span class="ArrowRight">></span> <span class="ArrowDown">v</span></a>
                            <div class="myContent">
                                <a class="" asp-area="" asp-controller="ExamPapers" asp-action="Index">Listele</a>
                                <a class="" asp-area="" asp-controller="ExamPapers" asp-action="Create">Yeni Oluştur</a>
                            </div>
                        </div>
                </div>
                @if (User.IsInRole("Admin"))
                    {
                        <div class="NavLeftItem">
                            <div class="myDropdown">
                                <a class="link" asp-area="Admin" asp-controller="Faculties" asp-action="Index">Fakülteler <span class="ArrowRight">></span> <span class="ArrowDown">v</span></a>
                                <div class="myContent">
                                    <a class="" asp-area="Admin" asp-controller="Faculties" asp-action="Index">Listele</a>
                                    <a class="" asp-area="Admin" asp-controller="Faculties" asp-action="Create">Yeni Oluştur</a>
                                </div>
                            </div>
                        </div>
                        <div class="NavLeftItem">
                            <div class="myDropdown">
                                <a class="link" asp-area="Admin" asp-controller="Departments" asp-action="Index">Bölümler <span class="ArrowRight">></span> <span class="ArrowDown">v</span></a>
                                <div class="myContent">
                                    <a class="" asp-area="Admin" asp-controller="Departments" asp-action="Index">Listele</a>
                                    <a class="" asp-area="Admin" asp-controller="Departments" asp-action="Create">Yeni Oluştur</a>
                                </div>
                            </div>

                        </div>

                        <div class="NavLeftItem">
                            <div class="myDropdown">
                                <a class="link" asp-area="Admin" asp-controller="Announcements" asp-action="Index">Duyurular <span class="ArrowRight">></span> <span class="ArrowDown">v</span></a>
                                <div class="myContent">
                                    <a class="" asp-area="Admin" asp-controller="Announcements" asp-action="Index">Listele</a>
                                    <a class="" asp-area="Admin" asp-controller="Announcements" asp-action="Create">Yeni Oluştur</a>
                                </div>
                            </div>

                        </div>
                    }                          
            </div>
            <div class="NavRight">
                @if (SignInManager.IsSignedIn(User))
                {
                    <div class="NavRightItem">
                            <a asp-controller="Home" asp-action="Index">Merhaba @User.Identity.Name!</a>
                    </div>
                    <div class="NavRightItem">
                        <form class="" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                            <button type="submit" class="">Çıkış</button>
                        </form>
                    </div>
                }
                else
                {
                    <div class="NavRightItem">
                        <a class="" asp-area="Identity" asp-page="/Account/Login"><i class="fa fa-user"></i>Giriş</a>
                    </div>
                    <div class="NavRightItem">
                        <a class="" asp-area="Identity" asp-page="/Account/Register"><i class="fa fa-bell"></i>Kayıt Ol</a>
                    </div>
                }
            </div>
        </nav>
    </header>
    }
    <div class="mid">
            @RenderBody()
    </div>

    <footer class="Footer">
        <div class="FooterMain">
            Yardıma ihtiyacınız mı var ?
            Admin@gmail.com'a mail atın.
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>